[mypy]
python_version = 3.12
strict = true

[mypy-feedparser.*]
ignore_missing_imports = true

[mypy-yaml.*]
ignore_missing_imports = true

[mypy-jobspy.*]
ignore_missing_imports = true

[mypy-pandas.*]
ignore_missing_imports = true
