"""
Candidate (company_name, greenhouse_slug) pairs used by probe_greenhouse_slugs.py
and will seed the MongoDB greenhouse_slugs collection (T19).

Add new entries here — keep grouped by sector for readability.
Slugs that return 404 are silently skipped during fetch, so unverified
entries are harmless.
"""

CANDIDATES: list[tuple[str, str]] = [
    # ── Confirmed valid ───────────────────────────────────────────────────────
    ("Postman", "postman"),
    ("Groww", "groww"),
    ("Slice", "slice"),
    ("PhonePe", "phonepe"),
    ("TCS", "tcs"),
    ("Airbnb", "airbnb"),
    ("Stripe", "stripe"),
    ("Twilio", "twilio"),
    ("Datadog", "datadog"),
    ("Cloudflare", "cloudflare"),
    ("PagerDuty", "pagerduty"),
    ("Okta", "okta"),
    ("Figma", "figma"),
    ("Vercel", "vercel"),
    ("Netlify", "netlify"),
    ("PlanetScale", "planetscale"),
    ("Cockroach Labs", "cockroachlabs"),
    ("Databricks", "databricks"),
    ("Fivetran", "fivetran"),
    ("Amplitude", "amplitude"),
    ("Mixpanel", "mixpanel"),
    ("LaunchDarkly", "launchdarkly"),
    ("Contentful", "contentful"),
    ("Storyblok", "storyblok"),
    ("Algolia", "algolia"),
    ("Elastic", "elastic"),
    ("MongoDB", "mongodb"),
    ("SingleStore", "singlestore"),
    ("Airtable", "airtable"),
    ("Digit Insurance", "digit"),

    # ── Hyperscalers / Big Tech ───────────────────────────────────────────────
    ("Google", "google"),
    ("Microsoft", "microsoft"),
    ("Amazon", "amazon"),
    ("Meta", "meta"),
    ("Apple", "apple"),
    ("Netflix", "netflix"),
    ("Uber", "uber"),
    ("LinkedIn", "linkedin"),
    ("Twitter", "twitter"),
    ("Snap", "snap"),
    ("Pinterest", "pinterest"),
    ("Shopify", "shopify"),
    ("Salesforce", "salesforce"),
    ("Oracle", "oracle"),
    ("SAP", "sap"),
    ("IBM", "ibm"),
    ("Dell", "dell"),
    ("HP", "hp"),
    ("Intel", "intel"),
    ("Qualcomm", "qualcomm"),
    ("NVIDIA", "nvidia"),
    ("AMD", "amd"),
    ("Cisco", "cisco"),
    ("VMware", "vmware"),
    ("ServiceNow", "servicenow"),
    ("Workday", "workday"),
    ("Adobe", "adobe"),
    ("Intuit", "intuit"),
    ("Autodesk", "autodesk"),
    ("Splunk", "splunk"),
    ("Palantir", "palantir"),
    ("Snowflake", "snowflake"),
    ("Databricks", "databricks"),
    ("Confluent", "confluent"),
    ("Cloudera", "cloudera"),
    ("Informatica", "informatica"),

    # ── Semiconductor / Hardware (large India R&D centers) ────────────────────
    ("Texas Instruments", "ti"),
    ("Broadcom", "broadcom"),
    ("Marvell", "marvell"),
    ("Arm", "arm"),
    ("Cadence", "cadence"),
    ("Synopsys", "synopsys"),
    ("Analog Devices", "analogdevices"),
    ("Microchip Technology", "microchip"),
    ("Silicon Labs", "silabs"),
    ("Maxim Integrated", "maximintegrated"),
    ("NXP Semiconductors", "nxp"),
    ("STMicroelectronics", "st"),
    ("Renesas", "renesas"),
    ("MediaTek", "mediatek"),
    ("Marvell Technology", "marvell"),
    ("Lattice Semiconductor", "latticesemi"),
    ("Xilinx", "xilinx"),
    ("Altera", "altera"),
    ("ASML", "asml"),
    ("Applied Materials", "appliedmaterials"),
    ("Lam Research", "lamresearch"),
    ("KLA", "kla"),
    ("Teradyne", "teradyne"),
    ("Keysight", "keysight"),
    ("National Instruments", "ni"),
    ("Trimble", "trimble"),
    ("Zebra Technologies", "zebra"),
    ("Datalogic", "datalogic"),
    ("Honeywell", "honeywell"),
    ("Emerson", "emerson"),
    ("Rockwell Automation", "rockwellautomation"),
    ("Siemens", "siemens"),
    ("Bosch", "bosch"),
    ("ABB", "abb"),
    ("Schneider Electric", "schneiderelectric"),
    ("Eaton", "eaton"),

    # ── Consulting / Services with large India centers ────────────────────────
    ("Thoughtworks", "thoughtworks"),
    ("EPAM Systems", "epam"),
    ("Globant", "globant"),
    ("Endava", "endava"),
    ("Nagarro", "nagarro"),
    ("Publicis Sapient", "publicissapient"),
    ("Capgemini", "capgemini"),
    ("Accenture", "accenture"),
    ("Deloitte", "deloitte"),
    ("McKinsey", "mckinsey"),
    ("BCG", "bcg"),
    ("Bain", "bain"),
    ("KPMG", "kpmg"),
    ("EY", "ey"),
    ("PwC", "pwc"),
    ("Slalom", "slalom"),
    ("Cognizant", "cognizant"),
    ("LTIMindtree", "ltimindtree"),
    ("Mphasis", "mphasis"),
    ("Hexaware", "hexaware"),
    ("Cyient", "cyient"),
    ("Persistent Systems", "persistent"),
    ("Zensar", "zensar"),
    ("NIIT Technologies", "niit"),
    ("Mastech", "mastech"),
    ("Sonata Software", "sonata"),
    ("Birlasoft", "birlasoft"),
    ("Coforge", "coforge"),
    ("KPIT Technologies", "kpit"),
    ("Sasken", "sasken"),
    ("Tata Elxsi", "tataelxsi"),
    ("QuEST Global", "questglobal"),
    ("Cybage", "cybage"),
    ("Xoriant", "xoriant"),
    ("Cuelogic", "cuelogic"),

    # ── Security ──────────────────────────────────────────────────────────────
    ("Palo Alto Networks", "paloaltonetworks"),
    ("CrowdStrike", "crowdstrike"),
    ("SentinelOne", "sentinelone"),
    ("Zscaler", "zscaler"),
    ("Fortinet", "fortinet"),
    ("Rapid7", "rapid7"),
    ("Tenable", "tenable"),
    ("Qualys", "qualys"),
    ("Snyk", "snyk"),
    ("Wiz", "wiz"),
    ("Lacework", "lacework"),
    ("Orca Security", "orcasecurity"),
    ("Aqua Security", "aquasecurity"),
    ("Sysdig", "sysdig"),
    ("Darktrace", "darktrace"),
    ("Abnormal Security", "abnormalsecurity"),
    ("Proofpoint", "proofpoint"),
    ("Mimecast", "mimecast"),
    ("KnowBe4", "knowbe4"),
    ("AttackIQ", "attackiq"),
    ("HackerOne", "hackerone"),
    ("Bugcrowd", "bugcrowd"),
    ("Cobalt", "cobalt"),
    ("XM Cyber", "xmcyber"),
    ("Tufin", "tufin"),
    ("FireMon", "firemon"),
    ("AlgoSec", "algosec"),
    ("Check Point", "checkpoint"),
    ("Cybereason", "cybereason"),
    ("Tanium", "tanium"),
    ("Veracode", "veracode"),
    ("NCC Group", "nccgroup"),
    ("Drata", "drata"),
    ("Vanta", "vanta"),
    ("Secureframe", "secureframe"),
    ("Anecdotes", "anecdotes"),
    ("Tugboat Logic", "tugboatlogic"),
    ("Sprinto", "sprinto"),
    ("Strike Graph", "strikegraph"),
    ("Scrut Automation", "scrut"),
    ("Thoropass", "thoropass"),
    ("Apptega", "apptega"),
    ("LogicGate", "logicgate"),
    ("ZenGRC", "zengrc"),
    ("Egnyte", "egnyte"),

    # ── Cloud / DevOps / Infra ────────────────────────────────────────────────
    ("HashiCorp", "hashicorp"),
    ("Grafana Labs", "grafana"),
    ("New Relic", "newrelic"),
    ("Dynatrace", "dynatrace"),
    ("Honeycomb", "honeycomb"),
    ("Chronosphere", "chronosphere"),
    ("Sumo Logic", "sumologic"),
    ("Sentry", "sentry"),
    ("CircleCI", "circleci"),
    ("Buildkite", "buildkite"),
    ("Harness", "harness"),
    ("JFrog", "jfrog"),
    ("Sonatype", "sonatype"),
    ("Pulumi", "pulumi"),
    ("Teleport", "teleport"),
    ("Kong", "kong"),
    ("Styra", "styra"),
    ("Coralogix", "coralogix"),
    ("Logz.io", "logzio"),
    ("Mezmo", "mezmo"),
    ("Rollbar", "rollbar"),
    ("Bugsnag", "bugsnag"),
    ("Lumigo", "lumigo"),
    ("Rancher", "rancher"),
    ("Portainer", "portainer"),
    ("Neon", "neon"),
    ("Turso", "turso"),
    ("PlanetScale", "planetscale"),
    ("Supabase", "supabase"),
    ("Railway", "railway"),
    ("Render", "render"),
    ("Fly.io", "flyio"),
    ("Inngest", "inngest"),
    ("Trigger.dev", "triggerdev"),
    ("Temporal", "temporal"),
    ("Conductor", "conductor"),
    ("Prefect", "prefect"),
    ("Dagster", "dagster"),
    ("Astronomer", "astronomer"),
    ("Mage", "mageai"),
    ("Kestra", "kestra"),
    ("Argo", "argoproj"),
    ("Codefresh", "codefresh"),
    ("Drone CI", "drone"),
    ("Semaphore", "semaphoreci"),
    ("Waypoint", "waypoint"),
    ("Porter", "porterdev"),
    ("Qovery", "qovery"),
    ("Northflank", "northflank"),
    ("Encore", "encore"),
    ("Depot", "depot"),
    ("Earthly", "earthly"),
    ("Dagger", "dagger"),

    # ── Data / Analytics / ML ─────────────────────────────────────────────────
    ("dbt Labs", "dbtlabs"),
    ("Airbyte", "airbyte"),
    ("Matillion", "matillion"),
    ("Alteryx", "alteryx"),
    ("Dremio", "dremio"),
    ("Starburst", "starburst"),
    ("ClickHouse", "clickhouse"),
    ("Materialize", "materialize"),
    ("Rockset", "rockset"),
    ("Tinybird", "tinybird"),
    ("Monte Carlo", "montecarlo"),
    ("Atlan", "atlan"),
    ("Alation", "alation"),
    ("Collibra", "collibra"),
    ("Weights & Biases", "wandb"),
    ("Hugging Face", "huggingface"),
    ("Scale AI", "scaleai"),
    ("Labelbox", "labelbox"),
    ("Roboflow", "roboflow"),
    ("Clarifai", "clarifai"),
    ("Runway", "runwayml"),
    ("Cohere", "cohere"),
    ("Anthropic", "anthropic"),
    ("OpenAI", "openai"),
    ("Together AI", "togetherai"),
    ("Replicate", "replicate"),
    ("Modal", "modal"),
    ("Anyscale", "anyscale"),
    ("Groq", "groq"),
    ("Cerebras", "cerebras"),
    ("SambaNova", "sambanova"),
    ("Graphcore", "graphcore"),
    ("Streamsets", "streamsets"),
    ("Meltano", "meltano"),
    ("Upsolver", "upsolver"),
    ("Acceldata", "acceldata"),
    ("Bigeye", "bigeye"),
    ("Great Expectations", "greatexpectations"),
    ("Soda", "soda"),
    ("Lightdash", "lightdash"),
    ("Metabase", "metabase"),
    ("Superset", "superset"),
    ("Redash", "redash"),
    ("Mode Analytics", "mode"),
    ("Sigma Computing", "sigmacomputing"),
    ("Hex", "hex"),
    ("Observable", "observable"),
    ("Deepnote", "deepnote"),
    ("Noteable", "noteable"),
    ("Databricks", "databricks"),
    ("Tecton", "tecton"),
    ("Feast", "feast"),
    ("Hopsworks", "hopsworks"),
    ("Featureform", "featureform"),
    ("Rasgo", "rasgo"),
    ("Chalk", "chalk"),
    ("Fennel", "fennel"),
    ("Arize AI", "arize"),
    ("WhyLabs", "whylabs"),
    ("Fiddler AI", "fiddler"),
    ("Arthur AI", "arthur"),
    ("Evidently AI", "evidently"),
    ("Aporia", "aporia"),
    ("Censius", "censius"),
    ("Superwise", "superwise"),
    ("NannyML", "nannyml"),
    ("Gantry", "gantry"),
    ("MLflow", "mlflow"),
    ("Weights & Biases", "wandb"),
    ("Comet ML", "cometml"),
    ("Neptune AI", "neptune"),
    ("ClearML", "clearml"),
    ("DVC", "dvc"),
    ("Valohai", "valohai"),
    ("Determined AI", "determinedai"),
    ("OctoML", "octoml"),
    ("BentoML", "bentoml"),
    ("Seldon", "seldon"),
    ("Cortex", "cortexlabs"),
    ("KServe", "kserve"),
    ("Kubeflow", "kubeflow"),
    ("ZenML", "zenml"),
    ("Metaflow", "metaflow"),
    ("Flyte", "flyte"),
    ("Kedro", "kedro"),
    ("Pachyderm", "pachyderm"),
    ("LakeFS", "lakefs"),
    ("Delta Lake", "deltalake"),
    ("Apache Iceberg", "iceberg"),
    ("Datalake", "datalake"),

    # ── Developer Tools ───────────────────────────────────────────────────────
    ("GitHub", "github"),
    ("GitLab", "gitlab"),
    ("Atlassian", "atlassian"),
    ("Asana", "asana"),
    ("Monday.com", "mondaydotcom"),
    ("ClickUp", "clickup"),
    ("Notion", "notion"),
    ("Linear", "linear"),
    ("Shortcut", "shortcut"),
    ("Coda", "coda"),
    ("GitBook", "gitbook"),
    ("Readme", "readme"),
    ("Stoplight", "stoplight"),
    ("RapidAPI", "rapidapi"),
    ("WorkOS", "workos"),
    ("Stytch", "stytch"),
    ("Clerk", "clerk"),
    ("Nango", "nango"),
    ("Merge", "merge"),
    ("Zapier", "zapier"),
    ("Pipedream", "pipedream"),
    ("Workato", "workato"),
    ("Tray.io", "trayio"),
    ("SnapLogic", "snaplogic"),
    ("Celigo", "celigo"),
    ("Jitterbit", "jitterbit"),
    ("Boomi", "boomi"),
    ("Retool", "retool"),
    ("Appsmith", "appsmith"),
    ("Tooljet", "tooljet"),
    ("Budibase", "budibase"),
    ("Directus", "directus"),
    ("Strapi", "strapi"),
    ("Sanity", "sanity"),
    ("Contentstack", "contentstack"),
    ("Hygraph", "hygraph"),
    ("Prismic", "prismic"),
    ("Butter CMS", "buttercms"),
    ("DatoCMS", "datocms"),
    ("Kontent.ai", "kontentai"),
    ("Agility CMS", "agilitycms"),
    ("Storyblok", "storyblok"),
    ("Umbraco", "umbraco"),
    ("Kentico", "kentico"),
    ("Optimizely", "optimizely"),
    ("Sitecore", "sitecore"),
    ("Acquia", "acquia"),
    ("WP Engine", "wpengine"),
    ("Kinsta", "kinsta"),
    ("Pantheon", "pantheon"),
    ("Netlify", "netlify"),
    ("Vercel", "vercel"),
    ("Layer0", "layer0"),
    ("Fastly", "fastly"),
    ("Akamai", "akamai"),
    ("Cloudflare", "cloudflare"),
    ("Imperva", "imperva"),
    ("Sucuri", "sucuri"),
    ("Sectigo", "sectigo"),
    ("DigiCert", "digicert"),
    ("Let's Encrypt", "letsencrypt"),
    ("Venafi", "venafi"),
    ("Keyfactor", "keyfactor"),
    ("AppViewX", "appviewx"),
    ("Entrust", "entrust"),

    # ── Messaging / Communication ─────────────────────────────────────────────
    ("Slack", "slack"),
    ("Discord", "discord"),
    ("Zoom", "zoom"),
    ("RingCentral", "ringcentral"),
    ("Vonage", "vonage"),
    ("Bandwidth", "bandwidth"),
    ("Telnyx", "telnyx"),
    ("Sinch", "sinch"),
    ("Plivo", "plivo"),
    ("Infobip", "infobip"),
    ("Twilio SendGrid", "sendgrid"),
    ("Mailgun", "mailgun"),
    ("Postmark", "postmark"),
    ("Iterable", "iterable"),
    ("Klaviyo", "klaviyo"),
    ("Braze", "braze"),
    ("Customer.io", "customerio"),
    ("ActiveCampaign", "activecampaign"),
    ("HubSpot", "hubspot"),
    ("Marketo", "marketo"),
    ("Gong", "gong"),
    ("Clari", "clari"),
    ("Outreach", "outreach"),
    ("SalesLoft", "salesloft"),
    ("Apollo", "apollo"),
    ("ZoomInfo", "zoominfo"),
    ("Clearbit", "clearbit"),
    ("Highspot", "highspot"),
    ("Seismic", "seismic"),
    ("Gainsight", "gainsight"),
    ("Totango", "totango"),
    ("ChurnZero", "churnzero"),
    ("Pendo", "pendo"),
    ("Appcues", "appcues"),
    ("Medallia", "medallia"),
    ("Qualtrics", "qualtrics"),
    ("Typeform", "typeform"),
    ("SurveyMonkey", "surveymonkey"),
    ("Podium", "podium"),
    ("Yotpo", "yotpo"),
    ("Birdeye", "birdeye"),
    ("Intercom", "intercom"),
    ("Zendesk", "zendesk"),
    ("Freshdesk", "freshdesk"),
    ("Drift", "drift"),
    ("Tidio", "tidio"),
    ("LiveChat", "livechat"),
    ("Olark", "olark"),
    ("Crisp", "crisp"),
    ("Chatwoot", "chatwoot"),
    ("Front", "front"),
    ("Groove", "groove"),
    ("Help Scout", "helpscout"),
    ("Kayako", "kayako"),
    ("Jira Service Management", "jiraservicemanagement"),
    ("Freshservice", "freshservice"),
    ("ServiceNow", "servicenow"),
    ("BMC Helix", "bmc"),
    ("Ivanti", "ivanti"),
    ("ManageEngine", "manageengine"),
    ("SolarWinds", "solarwinds"),
    ("ConnectWise", "connectwise"),
    ("Kaseya", "kaseya"),
    ("NinjaRMM", "ninjarmm"),
    ("Atera", "atera"),
    ("Syncro", "syncro"),

    # ── HR Tech / Recruiting ─────────────────────────────────────────────────
    ("Rippling", "rippling"),
    ("Gusto", "gusto"),
    ("Lattice", "lattice"),
    ("Culture Amp", "cultureamp"),
    ("15Five", "15five"),
    ("Betterworks", "betterworks"),
    ("Leapsome", "leapsome"),
    ("Cornerstone", "cornerstone"),
    ("Docebo", "docebo"),
    ("TalentLMS", "talentlms"),
    ("Paylocity", "paylocity"),
    ("Paycom", "paycom"),
    ("Justworks", "justworks"),
    ("Hibob", "hibob"),
    ("Personio", "personio"),
    ("Visier", "visier"),
    ("Eightfold AI", "eightfoldai"),
    ("Beamery", "beamery"),
    ("Phenom", "phenom"),
    ("iCIMS", "icims"),
    ("SmartRecruiters", "smartrecruiters"),
    ("Ashby", "ashby"),
    ("Gem", "gem"),
    ("Findem", "findem"),
    ("HireEZ", "hireez"),
    ("Seekout", "seekout"),
    ("BambooHR", "bamboohr"),
    ("ChartHop", "charthop"),
    ("Namely", "namely"),
    ("Greenhouse", "greenhouse"),
    ("Lever", "lever"),
    ("Workable", "workable"),
    ("Teamtailor", "teamtailor"),
    ("Recruitee", "recruitee"),
    ("Breezy HR", "breezyhr"),
    ("Jazz HR", "jazzhr"),
    ("Pinpoint", "pinpoint"),
    ("Factorial", "factorial"),
    ("Darwinbox", "darwinbox"),
    ("Keka", "keka"),
    ("greytHR", "greythr"),
    ("HROne", "hrone"),
    ("Zimyo", "zimyo"),
    ("Kredily", "kredily"),
    ("Sumhr", "sumhr"),
    ("PeopleStrong", "peoplestrong"),
    ("Spine HR", "spinehr"),
    ("Pocket HRMS", "pockethrms"),

    # ── Fintech (Global) ──────────────────────────────────────────────────────
    ("Plaid", "plaid"),
    ("Brex", "brex"),
    ("Ramp", "ramp"),
    ("Mercury", "mercury"),
    ("Chime", "chime"),
    ("Revolut", "revolut"),
    ("Wise", "wise"),
    ("Monzo", "monzo"),
    ("Nubank", "nubank"),
    ("Robinhood", "robinhood"),
    ("Coinbase", "coinbase"),
    ("Kraken", "kraken"),
    ("Chainalysis", "chainalysis"),
    ("TRM Labs", "trmlabs"),
    ("Sardine", "sardine"),
    ("Sift", "sift"),
    ("Forter", "forter"),
    ("Signifyd", "signifyd"),
    ("Checkout.com", "checkoutcom"),
    ("Adyen", "adyen"),
    ("Klarna", "klarna"),
    ("Affirm", "affirm"),
    ("dLocal", "dlocal"),
    ("Nuvei", "nuvei"),
    ("Rapyd", "rapyd"),
    ("Airwallex", "airwallex"),
    ("Payoneer", "payoneer"),
    ("Remitly", "remitly"),
    ("Nium", "nium"),
    ("Currencycloud", "currencycloud"),
    ("Tipalti", "tipalti"),
    ("Coupa", "coupa"),
    ("Jaggaer", "jaggaer"),
    ("Ivalua", "ivalua"),
    ("Zycus", "zycus"),
    ("Basware", "basware"),
    ("Tradeshift", "tradeshift"),
    ("Finastra", "finastra"),
    ("nCino", "ncino"),
    ("Mambu", "mambu"),
    ("Thought Machine", "thoughtmachine"),
    ("Backbase", "backbase"),
    ("Blend", "blend"),
    ("Better.com", "better"),
    ("FIS", "fis"),
    ("Fiserv", "fiserv"),
    ("Jack Henry", "jackhenry"),
    ("Q2", "q2"),
    ("Temenos", "temenos"),
    ("Sopra Banking", "soprabanking"),
    ("Avaloq", "avaloq"),
    ("Prometeia", "prometeia"),
    ("SS&C Technologies", "ssc"),
    ("SimCorp", "simcorp"),
    ("Broadridge", "broadridge"),
    ("FNZ", "fnz"),
    ("InvestCloud", "investcloud"),
    ("Advent Software", "advent"),
    ("Refinitiv", "refinitiv"),
    ("FactSet", "factset"),
    ("Bloomberg", "bloomberg"),
    ("S&P Global", "spglobal"),
    ("Morningstar", "morningstar"),
    ("Moody's Analytics", "moodysanalytics"),
    ("MSCI", "msci"),
    ("Verisk", "verisk"),
    ("LexisNexis Risk", "lexisnexis"),
    ("Dun & Bradstreet", "dnb"),
    ("TransUnion", "transunion"),
    ("Equifax", "equifax"),
    ("Experian", "experian"),

    # ── India fintech / SaaS ──────────────────────────────────────────────────
    ("Razorpay", "razorpay"),
    ("Zepto", "zepto"),
    ("Meesho", "meesho"),
    ("BrowserStack", "browserstack"),
    ("Freshworks", "freshworks"),
    ("Chargebee", "chargebee"),
    ("Hasura", "hasura"),
    ("Unacademy", "unacademy"),
    ("CRED", "cred"),
    ("KhataBook", "khatabook"),
    ("LeadSquared", "leadsquared"),
    ("Setu", "setu"),
    ("Juspay", "juspay"),
    ("Cashfree", "cashfree"),
    ("CleverTap", "clevertap"),
    ("MoEngage", "moengage"),
    ("WebEngage", "webengage"),
    ("Sprinklr", "sprinklr"),
    ("Tooljet", "tooljet"),
    ("Zerodha", "zerodha"),
    ("Smallcase", "smallcase"),
    ("INDmoney", "indmoney"),
    ("Groww", "groww"),
    ("Jupiter", "jupiter"),
    ("Fi Money", "fi"),
    ("Niyo", "niyo"),
    ("Perfios", "perfios"),
    ("Signzy", "signzy"),
    ("Jar", "jar"),
    ("BharatPe", "bharatpe"),
    ("PayU", "payu"),
    ("LazyPay", "lazypay"),
    ("Simpl", "simpl"),
    ("EarlySalary", "earlysalary"),
    ("KreditBee", "kreditbee"),
    ("MoneyTap", "moneytap"),
    ("Lendingkart", "lendingkart"),
    ("Capital Float", "capitalfloat"),
    ("Freo", "freo"),
    ("Open Financial", "open"),
    ("Instamojo", "instamojo"),
    ("Acko", "acko"),
    ("PolicyBazaar", "policybazaar"),
    ("Coverfox", "coverfox"),
    ("Turtlemint", "turtlemint"),
    ("Scripbox", "scripbox"),
    ("ET Money", "etmoney"),
    ("Kuvera", "kuvera"),
    ("Fisdom", "fisdom"),
    ("CoinDCX", "coindcx"),
    ("WazirX", "wazirx"),
    ("CoinSwitch", "coinswitch"),
    ("Mudrex", "mudrex"),

    # ── E-commerce / Logistics ────────────────────────────────────────────────
    ("BigCommerce", "bigcommerce"),
    ("Commercetools", "commercetools"),
    ("Elastic Path", "elasticpath"),
    ("Spryker", "spryker"),
    ("Vtex", "vtex"),
    ("Recharge", "recharge"),
    ("AfterShip", "aftership"),
    ("Shipbob", "shipbob"),
    ("ShipStation", "shipstation"),
    ("EasyPost", "easypost"),
    ("Shippo", "shippo"),
    ("Flexport", "flexport"),
    ("project44", "project44"),
    ("FourKites", "fourkites"),
    ("Samsara", "samsara"),
    ("Motive", "motive"),
    ("Convoy", "convoy"),
    ("Loadsmart", "loadsmart"),
    ("Flexe", "flexe"),
    ("Stord", "stord"),
    ("Narvar", "narvar"),
    ("Nykaa", "nykaa"),
    ("Meesho", "meesho"),
    ("Flipkart", "flipkart"),
    ("Myntra", "myntra"),
    ("Lenskart", "lenskart"),
    ("Pepperfry", "pepperfry"),
    ("Urban Ladder", "urbanladder"),
    ("Purplle", "purplle"),
    ("Mamaearth", "mamaearth"),
    ("Delhivery", "delhivery"),
    ("Shadowfax", "shadowfax"),
    ("Shiprocket", "shiprocket"),
    ("Ecom Express", "ecomexpress"),
    ("Loadshare", "loadshare"),
    ("BlackBuck", "blackbuck"),
    ("Rivigo", "rivigo"),
    ("Porter", "porter"),

    # ── SaaS / Productivity ───────────────────────────────────────────────────
    ("Dropbox", "dropbox"),
    ("Box", "box"),
    ("DocuSign", "docusign"),
    ("PandaDoc", "pandadoc"),
    ("Formstack", "formstack"),
    ("Grammarly", "grammarly"),
    ("Loom", "loom"),
    ("Miro", "miro"),
    ("Canva", "canva"),
    ("Framer", "framer"),
    ("Webflow", "webflow"),
    ("InVision", "invision"),
    ("Zeplin", "zeplin"),
    ("Abstract", "abstract"),
    ("Sketch", "sketch"),
    ("Otter.ai", "otter"),
    ("Fireflies.ai", "fireflies"),
    ("Gong", "gong"),
    ("Chorus", "chorus"),
    ("Wingman", "wingman"),
    ("Jiminny", "jiminny"),
    ("Grain", "grain"),
    ("Fathom", "fathom"),
    ("Avoma", "avoma"),
    ("Sembly", "sembly"),
    ("Tldv", "tldv"),
    ("Supernormal", "supernormal"),
    ("Read AI", "readai"),
    ("Fellow", "fellow"),
    ("Notiv", "notiv"),
    ("Hugo", "hugo"),
    ("Hypercontext", "hypercontext"),
    ("Range", "range"),
    ("Officevibe", "officevibe"),
    ("Donut", "donut"),
    ("Nectar HR", "nectarhr"),
    ("Bonusly", "bonusly"),
    ("Kazoo", "kazoo"),
    ("Motivosity", "motivosity"),
    ("Reward Gateway", "rewardgateway"),
    ("Achievers", "achievers"),
    ("Workhuman", "workhuman"),
    ("O.C. Tanner", "octanner"),

    # ── EdTech (Global) ───────────────────────────────────────────────────────
    ("Coursera", "coursera"),
    ("Udemy", "udemy"),
    ("edX", "edx"),
    ("Pluralsight", "pluralsight"),
    ("Duolingo", "duolingo"),
    ("Chegg", "chegg"),
    ("Quizlet", "quizlet"),
    ("Codecademy", "codecademy"),
    ("Springboard", "springboard"),
    ("HackerRank", "hackerrank"),
    ("upGrad", "upgrad"),
    ("Great Learning", "greatlearning"),
    ("Simplilearn", "simplilearn"),
    ("Scaler", "scaler"),
    ("Internshala", "internshala"),
    ("Vedantu", "vedantu"),
    ("Unacademy", "unacademy"),
    ("Physics Wallah", "physicswallah"),
    ("Classplus", "classplus"),
    ("Teachmint", "teachmint"),
    ("Extramarks", "extramarks"),
    ("AlmaBetter", "almabetter"),
    ("Coding Ninjas", "codingninjas"),
    ("NxtWave", "nxtwave"),

    # ── Healthtech / Biotech ──────────────────────────────────────────────────
    ("Veeva Systems", "veeva"),
    ("Health Catalyst", "healthcatalyst"),
    ("Tempus", "tempus"),
    ("Guardant Health", "guardanthealth"),
    ("Illumina", "illumina"),
    ("10x Genomics", "10xgenomics"),
    ("Recursion", "recursion"),
    ("Ginkgo Bioworks", "ginkgobioworks"),
    ("Twist Bioscience", "twistbioscience"),
    ("Schrodinger", "schrodinger"),
    ("Exscientia", "exscientia"),
    ("BenevolentAI", "benevolentai"),
    ("AbSci", "absci"),
    ("athenahealth", "athenahealth"),
    ("Inovalon", "inovalon"),
    ("Waystar", "waystar"),
    ("Netsmart", "netsmart"),
    ("Cotiviti", "cotiviti"),
    ("Availity", "availity"),
    ("Practo", "practo"),
    ("MediBuddy", "medibuddy"),
    ("HealthifyMe", "healthifyme"),
    ("Cure.fit", "curefit"),
    ("Pristyn Care", "pristyncare"),
    ("1mg", "1mg"),
    ("PharmEasy", "pharmeasy"),
    ("Netmeds", "netmeds"),
    ("Portea", "portea"),
    ("mfine", "mfine"),

    # ── Media / Entertainment ─────────────────────────────────────────────────
    ("Spotify", "spotify"),
    ("SoundCloud", "soundcloud"),
    ("Deezer", "deezer"),
    ("Tidal", "tidal"),
    ("Pandora", "pandora"),
    ("iHeartRadio", "iheartradio"),
    ("Audible", "audible"),
    ("Scribd", "scribd"),
    ("Flipboard", "flipboard"),
    ("Feedly", "feedly"),
    ("Substack", "substack"),
    ("Ghost", "ghost"),
    ("Beehiiv", "beehiiv"),
    ("WordPress", "wordpress"),
    ("Wix", "wix"),
    ("Squarespace", "squarespace"),
    ("Webflow", "webflow"),

    # ── Gaming ────────────────────────────────────────────────────────────────
    ("Riot Games", "riotgames"),
    ("Epic Games", "epicgames"),
    ("Unity", "unity"),
    ("Niantic", "niantic"),
    ("Zynga", "zynga"),
    ("Supercell", "supercell"),
    ("Scopely", "scopely"),
    ("Kabam", "kabam"),
    ("Plarium", "plarium"),
    ("Wargaming", "wargaming"),
    ("Gameloft", "gameloft"),
    ("InnoGames", "innogames"),
    ("Dream11", "dream11"),
    ("MPL", "mpl"),
    ("WinZO", "winzo"),
    ("Games24x7", "games24x7"),

    # ── Travel / Hospitality ──────────────────────────────────────────────────
    ("Booking.com", "bookingcom"),
    ("Expedia", "expedia"),
    ("TripAdvisor", "tripadvisor"),
    ("Hopper", "hopper"),
    ("Skyscanner", "skyscanner"),
    ("Kiwi.com", "kiwicom"),
    ("MakeMyTrip", "makemytrip"),
    ("Ixigo", "ixigo"),
    ("EaseMyTrip", "easemytrip"),
    ("Yatra", "yatra"),
    ("Cleartrip", "cleartrip"),
    ("OYO", "oyo"),
    ("Treebo", "treebo"),
    ("FabHotels", "fabhotels"),

    # ── Real Estate / PropTech ────────────────────────────────────────────────
    ("Opendoor", "opendoor"),
    ("Compass", "compass"),
    ("Redfin", "redfin"),
    ("Zillow", "zillow"),
    ("HomeLight", "homelight"),
    ("Snapdocs", "snapdocs"),
    ("Notarize", "notarize"),
    ("NoBroker", "nobroker"),
    ("Housing.com", "housing"),
    ("99acres", "99acres"),
    ("Magicbricks", "magicbricks"),
    ("Square Yards", "squareyards"),
    ("PropTiger", "proptiger"),
    ("NestAway", "nestaway"),
    ("Stanza Living", "stanzaliving"),
    ("Zolo", "zolo"),
    ("Housr", "housr"),
    ("Colive", "colive"),
]
