"""
Candidate (company_name, greenhouse_slug) pairs for probe_greenhouse_slugs.py.
Add new entries here — the prober picks them up automatically.
"""

CANDIDATES: list[tuple[str, str]] = [
    # ── Already confirmed valid ───────────────────────────────────────────────
    ("Postman", "postman"),
    ("Groww", "groww"),
    ("Slice", "slice"),
    ("PhonePe", "phonepe"),
    ("TCS", "tcs"),
    ("Airbnb", "airbnb"),
    ("Stripe", "stripe"),
    ("Twilio", "twilio"),
    ("Datadog", "datadog"),
    ("Cloudflare", "cloudflare"),
    ("PagerDuty", "pagerduty"),
    ("Okta", "okta"),
    ("Figma", "figma"),
    ("Vercel", "vercel"),
    ("Netlify", "netlify"),
    ("PlanetScale", "planetscale"),
    ("Cockroach Labs", "cockroachlabs"),
    ("Databricks", "databricks"),
    ("Fivetran", "fivetran"),
    ("Amplitude", "amplitude"),
    ("Mixpanel", "mixpanel"),
    ("LaunchDarkly", "launchdarkly"),
    ("Contentful", "contentful"),
    ("Storyblok", "storyblok"),
    ("Algolia", "algolia"),
    ("Elastic", "elastic"),
    ("MongoDB", "mongodb"),
    ("SingleStore", "singlestore"),
    ("Airtable", "airtable"),
    ("Digit Insurance", "digit"),

    # ── Hyperscalers / Big Tech ───────────────────────────────────────────────
    ("Google", "google"),
    ("Microsoft", "microsoft"),
    ("Amazon", "amazon"),
    ("Meta", "meta"),
    ("Apple", "apple"),
    ("Netflix", "netflix"),
    ("Uber", "uber"),
    ("LinkedIn", "linkedin"),
    ("Twitter", "twitter"),
    ("Snap", "snap"),
    ("Pinterest", "pinterest"),
    ("Shopify", "shopify"),
    ("Salesforce", "salesforce"),
    ("Oracle", "oracle"),
    ("SAP", "sap"),
    ("IBM", "ibm"),
    ("Dell", "dell"),
    ("HP", "hp"),
    ("Intel", "intel"),
    ("Qualcomm", "qualcomm"),
    ("NVIDIA", "nvidia"),
    ("AMD", "amd"),
    ("Cisco", "cisco"),
    ("VMware", "vmware"),
    ("ServiceNow", "servicenow"),
    ("Workday", "workday"),
    ("Adobe", "adobe"),
    ("Intuit", "intuit"),
    ("Autodesk", "autodesk"),
    ("Splunk", "splunk"),

    # ── Security ──────────────────────────────────────────────────────────────
    ("Palo Alto Networks", "paloaltonetworks"),
    ("CrowdStrike", "crowdstrike"),
    ("SentinelOne", "sentinelone"),
    ("Zscaler", "zscaler"),
    ("Fortinet", "fortinet"),
    ("Rapid7", "rapid7"),
    ("Tenable", "tenable"),
    ("Qualys", "qualys"),
    ("Snyk", "snyk"),
    ("Wiz", "wiz"),
    ("Lacework", "lacework"),
    ("Orca Security", "orcasecurity"),
    ("Aqua Security", "aquasecurity"),
    ("Sysdig", "sysdig"),
    ("Darktrace", "darktrace"),
    ("Vectra AI", "vectraai"),
    ("Abnormal Security", "abnormalsecurity"),
    ("Proofpoint", "proofpoint"),
    ("Mimecast", "mimecast"),
    ("Barracuda", "barracuda"),
    ("Cofense", "cofense"),
    ("KnowBe4", "knowbe4"),
    ("AttackIQ", "attackiq"),
    ("SafeBreach", "safebreach"),
    ("HackerOne", "hackerone"),
    ("Bugcrowd", "bugcrowd"),
    ("Synack", "synack"),
    ("Cobalt", "cobalt"),
    ("Pentera", "pentera"),
    ("XM Cyber", "xmcyber"),
    ("Tufin", "tufin"),
    ("FireMon", "firemon"),
    ("AlgoSec", "algosec"),
    ("Check Point", "checkpoint"),
    ("Cybereason", "cybereason"),
    ("Tanium", "tanium"),
    ("Veracode", "veracode"),
    ("Synopsys", "synopsys"),
    ("NCC Group", "nccgroup"),

    # ── Cloud / DevOps / Infra ────────────────────────────────────────────────
    ("HashiCorp", "hashicorp"),
    ("Grafana Labs", "grafana"),
    ("New Relic", "newrelic"),
    ("Dynatrace", "dynatrace"),
    ("Honeycomb", "honeycomb"),
    ("Chronosphere", "chronosphere"),
    ("Sumo Logic", "sumologic"),
    ("Sentry", "sentry"),
    ("CircleCI", "circleci"),
    ("Buildkite", "buildkite"),
    ("Harness", "harness"),
    ("JFrog", "jfrog"),
    ("Sonatype", "sonatype"),
    ("Pulumi", "pulumi"),
    ("Teleport", "teleport"),
    ("Kong", "kong"),
    ("Traefik", "traefik"),
    ("Styra", "styra"),
    ("Solo.io", "soloio"),
    ("Coralogix", "coralogix"),
    ("Logz.io", "logzio"),
    ("Mezmo", "mezmo"),
    ("Rollbar", "rollbar"),
    ("Bugsnag", "bugsnag"),
    ("Lumigo", "lumigo"),
    ("Serverless", "serverless"),
    ("Rancher", "rancher"),
    ("Portainer", "portainer"),

    # ── Data / Analytics / ML ─────────────────────────────────────────────────
    ("Snowflake", "snowflake"),
    ("dbt Labs", "dbtlabs"),
    ("Airbyte", "airbyte"),
    ("Matillion", "matillion"),
    ("Informatica", "informatica"),
    ("Talend", "talend"),
    ("Alteryx", "alteryx"),
    ("Palantir", "palantir"),
    ("Cloudera", "cloudera"),
    ("Dremio", "dremio"),
    ("Starburst", "starburst"),
    ("ClickHouse", "clickhouse"),
    ("Materialize", "materialize"),
    ("Rockset", "rockset"),
    ("Tinybird", "tinybird"),
    ("Monte Carlo Data", "montecarlodata"),
    ("Atlan", "atlan"),
    ("Alation", "alation"),
    ("Collibra", "collibra"),
    ("Weights & Biases", "wandb"),
    ("Hugging Face", "huggingface"),
    ("Scale AI", "scaleai"),
    ("Labelbox", "labelbox"),
    ("Snorkel AI", "snorkelai"),
    ("Roboflow", "roboflow"),
    ("Clarifai", "clarifai"),
    ("Runway", "runwayml"),
    ("Stability AI", "stabilityai"),
    ("Cohere", "cohere"),
    ("Anthropic", "anthropic"),
    ("OpenAI", "openai"),
    ("Together AI", "togetherai"),
    ("Replicate", "replicate"),
    ("Modal", "modal"),
    ("Anyscale", "anyscale"),
    ("OctoML", "octoml"),
    ("Groq", "groq"),
    ("Cerebras", "cerebras"),
    ("SambaNova", "sambanova"),
    ("Graphcore", "graphcore"),
    ("Fivetran", "fivetran"),
    ("StreamSets", "streamsets"),
    ("Meltano", "meltano"),
    ("Upsolver", "upsolver"),
    ("Airbyte", "airbyte"),
    ("Acceldata", "acceldata"),
    ("Bigeye", "bigeye"),
    ("Great Expectations", "greatexpectations"),
    ("Soda", "soda"),

    # ── Developer Tools ───────────────────────────────────────────────────────
    ("GitHub", "github"),
    ("GitLab", "gitlab"),
    ("Atlassian", "atlassian"),
    ("Asana", "asana"),
    ("Monday.com", "mondaydotcom"),
    ("ClickUp", "clickup"),
    ("Notion", "notion"),
    ("Linear", "linear"),
    ("Shortcut", "shortcut"),
    ("Coda", "coda"),
    ("GitBook", "gitbook"),
    ("Readme", "readme"),
    ("Stoplight", "stoplight"),
    ("RapidAPI", "rapidapi"),
    ("Apigee", "apigee"),
    ("WorkOS", "workos"),
    ("Stytch", "stytch"),
    ("Clerk", "clerk"),
    ("Nango", "nango"),
    ("Merge", "merge"),
    ("Zapier", "zapier"),
    ("n8n", "n8n"),
    ("Pipedream", "pipedream"),
    ("Workato", "workato"),
    ("Tray.io", "trayio"),
    ("SnapLogic", "snaplogic"),
    ("Celigo", "celigo"),
    ("Jitterbit", "jitterbit"),
    ("Boomi", "boomi"),

    # ── Messaging / Communication ─────────────────────────────────────────────
    ("Slack", "slack"),
    ("Discord", "discord"),
    ("Zoom", "zoom"),
    ("RingCentral", "ringcentral"),
    ("Vonage", "vonage"),
    ("MessageBird", "messagebird"),
    ("Bandwidth", "bandwidth"),
    ("Telnyx", "telnyx"),
    ("Sinch", "sinch"),
    ("Plivo", "plivo"),
    ("Infobip", "infobip"),
    ("Twilio SendGrid", "sendgrid"),
    ("Mailgun", "mailgun"),
    ("Postmark", "postmark"),
    ("Iterable", "iterable"),
    ("Klaviyo", "klaviyo"),
    ("Braze", "braze"),
    ("Customer.io", "customerio"),
    ("ActiveCampaign", "activecampaign"),
    ("HubSpot", "hubspot"),
    ("Marketo", "marketo"),
    ("Gong", "gong"),
    ("Clari", "clari"),
    ("Outreach", "outreach"),
    ("SalesLoft", "salesloft"),
    ("Apollo", "apollo"),
    ("ZoomInfo", "zoominfo"),
    ("Clearbit", "clearbit"),
    ("Highspot", "highspot"),
    ("Seismic", "seismic"),
    ("Gainsight", "gainsight"),
    ("Totango", "totango"),
    ("ChurnZero", "churnzero"),
    ("Pendo", "pendo"),
    ("Appcues", "appcues"),
    ("Medallia", "medallia"),
    ("Qualtrics", "qualtrics"),
    ("Typeform", "typeform"),
    ("SurveyMonkey", "surveymonkey"),
    ("Podium", "podium"),
    ("Yotpo", "yotpo"),
    ("Trustpilot", "trustpilot"),
    ("Birdeye", "birdeye"),

    # ── HR Tech / Recruiting ─────────────────────────────────────────────────
    ("Rippling", "rippling"),
    ("Gusto", "gusto"),
    ("Lattice", "lattice"),
    ("Culture Amp", "cultureamp"),
    ("15Five", "15five"),
    ("Betterworks", "betterworks"),
    ("Leapsome", "leapsome"),
    ("Cornerstone", "cornerstone"),
    ("Docebo", "docebo"),
    ("TalentLMS", "talentlms"),
    ("Paylocity", "paylocity"),
    ("Paycom", "paycom"),
    ("Justworks", "justworks"),
    ("Hibob", "hibob"),
    ("Personio", "personio"),
    ("Visier", "visier"),
    ("Eightfold AI", "eightfoldai"),
    ("Beamery", "beamery"),
    ("Phenom", "phenom"),
    ("iCIMS", "icims"),
    ("SmartRecruiters", "smartrecruiters"),
    ("Ashby", "ashby"),
    ("Gem", "gem"),
    ("Findem", "findem"),
    ("HireEZ", "hireez"),
    ("Seekout", "seekout"),
    ("BambooHR", "bamboohr"),
    ("ChartHop", "charthop"),
    ("Namely", "namely"),
    ("Greenhouse", "greenhouse"),
    ("Lever", "lever"),

    # ── Fintech (Global) ──────────────────────────────────────────────────────
    ("Plaid", "plaid"),
    ("Brex", "brex"),
    ("Ramp", "ramp"),
    ("Mercury", "mercury"),
    ("Chime", "chime"),
    ("Revolut", "revolut"),
    ("Wise", "wise"),
    ("Monzo", "monzo"),
    ("N26", "n26"),
    ("Nubank", "nubank"),
    ("Robinhood", "robinhood"),
    ("Coinbase", "coinbase"),
    ("Kraken", "kraken"),
    ("Gemini", "gemini"),
    ("Chainalysis", "chainalysis"),
    ("TRM Labs", "trmlabs"),
    ("Sardine", "sardine"),
    ("Sift", "sift"),
    ("Forter", "forter"),
    ("Signifyd", "signifyd"),
    ("Riskified", "riskified"),
    ("Checkout.com", "checkoutcom"),
    ("Adyen", "adyen"),
    ("Mollie", "mollie"),
    ("Klarna", "klarna"),
    ("Affirm", "affirm"),
    ("dLocal", "dlocal"),
    ("Nuvei", "nuvei"),
    ("Rapyd", "rapyd"),
    ("Airwallex", "airwallex"),
    ("Payoneer", "payoneer"),
    ("Remitly", "remitly"),
    ("Nium", "nium"),
    ("Currencycloud", "currencycloud"),
    ("Tipalti", "tipalti"),
    ("Bill.com", "billdotcom"),
    ("Expensify", "expensify"),
    ("Spendesk", "spendesk"),
    ("Pleo", "pleo"),
    ("Payhawk", "payhawk"),
    ("Coupa", "coupa"),
    ("Jaggaer", "jaggaer"),
    ("Ivalua", "ivalua"),
    ("Zycus", "zycus"),
    ("GEP", "gep"),
    ("Basware", "basware"),
    ("Tradeshift", "tradeshift"),
    ("Finastra", "finastra"),
    ("nCino", "ncino"),
    ("Mambu", "mambu"),
    ("Thought Machine", "thoughtmachine"),
    ("Backbase", "backbase"),
    ("Blend", "blend"),
    ("Better.com", "better"),

    # ── E-commerce / Logistics ────────────────────────────────────────────────
    ("BigCommerce", "bigcommerce"),
    ("Commercetools", "commercetools"),
    ("Elastic Path", "elasticpath"),
    ("Spryker", "spryker"),
    ("Vtex", "vtex"),
    ("Recharge", "recharge"),
    ("AfterShip", "aftership"),
    ("Shipbob", "shipbob"),
    ("ShipStation", "shipstation"),
    ("EasyPost", "easypost"),
    ("Shippo", "shippo"),
    ("Flexport", "flexport"),
    ("project44", "project44"),
    ("FourKites", "fourkites"),
    ("Samsara", "samsara"),
    ("Motive", "motive"),
    ("Transfix", "transfix"),
    ("Convoy", "convoy"),
    ("Loadsmart", "loadsmart"),
    ("Flexe", "flexe"),
    ("Stord", "stord"),
    ("Narvar", "narvar"),

    # ── SaaS / Productivity ───────────────────────────────────────────────────
    ("Dropbox", "dropbox"),
    ("Box", "box"),
    ("DocuSign", "docusign"),
    ("PandaDoc", "pandadoc"),
    ("Formstack", "formstack"),
    ("Qualtrics", "qualtrics"),
    ("Grammarly", "grammarly"),
    ("Loom", "loom"),
    ("Miro", "miro"),
    ("Canva", "canva"),
    ("Framer", "framer"),
    ("Webflow", "webflow"),
    ("InVision", "invision"),
    ("Zeplin", "zeplin"),
    ("Abstract", "abstract"),
    ("Sketch", "sketch"),

    # ── EdTech (Global) ───────────────────────────────────────────────────────
    ("Coursera", "coursera"),
    ("Udemy", "udemy"),
    ("edX", "edx"),
    ("Pluralsight", "pluralsight"),
    ("Duolingo", "duolingo"),
    ("Chegg", "chegg"),
    ("Quizlet", "quizlet"),
    ("Codecademy", "codecademy"),
    ("Springboard", "springboard"),
    ("HackerRank", "hackerrank"),

    # ── Healthtech / Biotech ──────────────────────────────────────────────────
    ("Veeva Systems", "veeva"),
    ("Health Catalyst", "healthcatalyst"),
    ("Tempus", "tempus"),
    ("Guardant Health", "guardanthealth"),
    ("Illumina", "illumina"),
    ("10x Genomics", "10xgenomics"),
    ("Recursion", "recursion"),
    ("Ginkgo Bioworks", "ginkgobioworks"),
    ("Twist Bioscience", "twistbioscience"),
    ("Schrodinger", "schrodinger"),
    ("Exscientia", "exscientia"),
    ("BenevolentAI", "benevolentai"),
    ("AbSci", "absci"),
    ("athenahealth", "athenahealth"),
    ("Inovalon", "inovalon"),
    ("Waystar", "waystar"),
    ("Netsmart", "netsmart"),
    ("Cotiviti", "cotiviti"),
    ("Availity", "availity"),

    # ── Media / Entertainment ─────────────────────────────────────────────────
    ("Spotify", "spotify"),
    ("SoundCloud", "soundcloud"),
    ("Deezer", "deezer"),
    ("Tidal", "tidal"),
    ("Pandora", "pandora"),
    ("iHeartRadio", "iheartradio"),
    ("Audible", "audible"),
    ("Scribd", "scribd"),
    ("Flipboard", "flipboard"),
    ("Feedly", "feedly"),

    # ── Gaming ────────────────────────────────────────────────────────────────
    ("Riot Games", "riotgames"),
    ("Epic Games", "epicgames"),
    ("Unity", "unity"),
    ("Niantic", "niantic"),
    ("Zynga", "zynga"),
    ("Supercell", "supercell"),
    ("Scopely", "scopely"),
    ("Kabam", "kabam"),
    ("Plarium", "plarium"),
    ("Wargaming", "wargaming"),
    ("Gameloft", "gameloft"),
    ("InnoGames", "innogames"),

    # ── Travel / Hospitality ──────────────────────────────────────────────────
    ("Booking.com", "bookingcom"),
    ("Expedia", "expedia"),
    ("TripAdvisor", "tripadvisor"),
    ("Hopper", "hopper"),
    ("Skyscanner", "skyscanner"),
    ("Kiwi.com", "kiwicom"),

    # ── Real Estate / PropTech ────────────────────────────────────────────────
    ("Opendoor", "opendoor"),
    ("Compass", "compass"),
    ("Redfin", "redfin"),
    ("Zillow", "zillow"),
    ("HomeLight", "homelight"),
    ("Better.com", "better"),
    ("Snapdocs", "snapdocs"),
    ("Notarize", "notarize"),

    # ── India fintech / new additions ─────────────────────────────────────────
    ("Razorpay", "razorpay"),
    ("Zepto", "zepto"),
    ("Meesho", "meesho"),
    ("BrowserStack", "browserstack"),
    ("Freshworks", "freshworks"),
    ("Chargebee", "chargebee"),
    ("Hasura", "hasura"),
    ("Unacademy", "unacademy"),
    ("CRED", "cred"),
    ("KhataBook", "khatabook"),
    ("LeadSquared", "leadsquared"),
    ("Setu", "setu"),
    ("Juspay", "juspay"),
    ("Cashfree", "cashfree"),
    ("CleverTap", "clevertap"),
    ("MoEngage", "moengage"),
    ("WebEngage", "webengage"),
    ("Darwinbox", "darwinbox"),
    ("Sprinklr", "sprinklr"),
    ("Appsmith", "appsmith"),
    ("Tooljet", "tooljet"),
]
